config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  get "/commit_sentiments", to: "repos#commit_sentiments"
  get "/repos/:id/badge", to: "repos#badge", format: :svg

  resources :users
  resources :repos

  get    '/login',                   to: "sessions#new"
  get    '/auth/:provider/callback', to: "sessions#create_with_provider"
  post   '/login',                   to: "sessions#create"
  delete '/logout',                  to: "sessions#destroy"
end

app/models/repo.rb
class Repo < ActiveRecord::Base
  validates :owner, :name, presence: true
  validates :private, exclusion: { in: [nil] }

  def request_repo
    Faraday.get "https://api.github.com/repos/#{owner}/#{name}" do |request|
      request.params['client_id'] = ENV['GITHUB_KEY']
      request.params['client_secret'] = ENV['GITHUB_SECRET']
    end
  end

  def request_commits
    Faraday.get "https://api.github.com/repos/#{owner}/#{name}/commits" do |request|
      request.params['client_id'] = ENV['GITHUB_KEY']
      request.params['client_secret'] = ENV['GITHUB_SECRET']
    end
  end

  def set_privacy
    self.private = repo_info[:private]
  end

  def private?
    private
  end

  def repo_info
    @repo_info ||= JSON.parse request_repo.body, { symbolize_names: true }
  end

  def commits
    @commits ||= JSON.parse request_commits.body, { symbolize_names: true }
  end

  def messages
    commits.map{ |commit| commit[:commit][:message] }
  end

  def analyze_sentiment(commit)
    (Sentimentalizer.analyze(commit).overall_probability * 100).round
  end

  def mood_color
    colors = ["#e34a33", "#fdbb84", "#fee8c8", "#e5f5f9", "#99d8c9", "#99d8c9"]
    colors.at(((mood.to_f/100)*5).round)
  end

  def badge
    "<svg width='52px' height='52px' xmlns='http://www.w3.org/2000/svg'>
    <circle cx='30' cy='30' r='20' stroke='#{mood_color}' stroke-width='3' fill='white' />
    <text x='30' y='35' font-size='16px' font-family='Helvetica Neue' font-weight='100' text-anchor='middle' >#{ mood.to_s }</text>
    </svg>"
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { |user| user.email = email.downcase }
  VALID_EMAIL = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: true, format: { with: VALID_EMAIL }
  validates :name, presence: true

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth['provider']
      user.uid      = auth['uid']
      user.token    = auth['credentials']['token']
      user.name     = auth['info']['name']
      user.email    = auth['info']['email']
      user.avatar   = auth['info']['image']
    end
  end

  def request_user
    Faraday.get "https://api.github.com/user/repos" do |request|
      request.params['access_token'] = token
      request.headers['Accept'] = 'application/vnd.github.moondragon+json'
    end
  end

  def repos_response
    @repos_response ||= JSON.parse request_user.body, { symbolize_names: true }
  end

  def public_repos
    repos_response.reject { |repo| repo[:private] }.map { |repo| repo[:full_name] }
  end

  def private_repos
    repos_response.select { |repo| repo[:private] }.map { |repo| repo[:full_name] }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @repo = Repo.new
  end
end

app/controllers/repos_controller.rb
require 'reloader/sse'

class ReposController < ApplicationController
  include ActionController::Live

  def commit_sentiments
    @repo = Repo.find(params[:id])
    response.headers['Content-Type'] = 'text/event-stream'
    sse = Reloader::SSE.new(response.stream)
    begin
      @repo.messages.each do |msg|
        senti = @repo.analyze_sentiment(msg)
        sse.write({ msg: msg, score: senti})
      end
      sse.write("stream_end")
    rescue IOError
    ensure
      sse.close
    end
  end

  def create
    @repo = Repo.new(repo_params)
    @repo.set_privacy
    respond_to do |format|
      if @repo.save
        format.js { }
      else
        format.js { render "failed" }
      end
    end
  end

  def new
    owner, name = params[:repo].split("/")
    @repo = Repo.new(owner: owner, name: name)
    @repo.set_privacy
    redirect_to repo_path @repo if @repo.save
  end

  def badge
    @repo = Repo.find(params[:id])
    svg = @repo.badge
    respond_to do |format|
      format.svg { render inline: svg }
    end
  end

  def index
  end

  def show
    @repo = Repo.find(params[:id])
  end
  
  def update
    repo = Repo.find(params[:id])
    mood = params[:mood].to_i / 30
    repo.update_attributes(mood: mood)
    render nothing: true
  end

  private

  def repo_params
    params.require(:repo).permit(:owner, :name)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create_with_provider
    auth = request.env["omniauth.auth"]
    user = User.find_by_provider_and_uid(auth["provider"], auth["uid"]) || User.create_with_omniauth(auth)

    if user
      session[:user_id] = user.id
      redirect_to user_path user
    else
      redirect_to root_url
    end
  end

  def destroy
    session.clear
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
   @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url
    else
      render :back
    end
  end

  def show
    @user = User.find(params[:id])
    @token = session[:token]
  end

  private

  def user_params
    params.require(:user).permit(:email, :name, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-custom" role="navigation">
<% if !current_page? root_url %>
<ul class="nav navbar-nav navbar-left">
<li><%= link_to "Mood Ring", root_path %></li>
</ul>
<% end %>
<ul class="nav navbar-nav navbar-right text-right">
  <% if current_user %>
    <div class="dropdown">
      <a data-toggle="dropdown">
        <%= image_tag current_user.avatar, class: "img-responsive img-circle avatar" %>
      </a>
      <ul class="dropdown-menu">
        <li><%= link_to "Profile", user_path(current_user) %></li>
        <li><%= link_to "Logout", logout_path, method: 'delete' %></li>
      </ul>
    </div>
  <% else %>
    <li><a href="/auth/github"><i class="fa fa-github"></i></a></li>
  <% end %>
</ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MoodRing</title>
    <%= favicon_link_tag 'favicon.png' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body class="<%= controller_name %> <%= action_name %>">
    <div class="container">
      <%= render 'layouts/navbar' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/_header.html.erb
<header class="intro">
<div class="intro-body">
  <div class="container">
    <div class="row">
      <div class="col-md-8 col-md-offset-2">
        <h1 class="brand-heading">Mood<br>Ring</h1>
        <div class="row">
          <%= form_for @repo, html: {id: 'repoForm'}, remote: true do |f| %>
            <div id="circle"></div>
            <p>github.com/
            <%= f.text_field :owner, class: "github-repo", placeholder: "dglunz" %>/
            <%= f.text_field :name, class: "github-repo", placeholder: "moodring" %>
            </p>
          <% end %>
        </div>
        <div class="row mood-details"></div>
      </div>
    </div>
  </div>
</div>
</header>

app/views/pages/home.html.erb
<%= render partial: 'header' %>

app/views/partials/_log_in.html.erb
<a href="#" data-toggle="modal" data-target="#myModalLogIn">
  Login
</a>
<div class="modal fade" id="myModalLogIn" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel">Log into your account</h3>
      </div>
      <div class="modal-body">
        <div class="edit-form">
          <div class='form-group new-user-form'>
            <%= form_tag login_path, method: :post do %>
              <%= text_field_tag :email_address, nil, placeholder: "email address", class: "modal-form form-control" %><br>
              <%= password_field_tag :password, nil, placeholder: "password", class: "modal-form form-control" %><br>
              <%= submit_tag "Login", class: "btn btn-default" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/partials/_login.html.erb
<a href="#" data-toggle="modal" data-target="#myModalLogIn">
  <i class="fa fa-github"></i>
</a>
<div class="modal fade" id="myModalLogIn" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel">Log into your account</h3>
      </div>
      <div class="modal-body">
        <div class="edit-form">
          <div class='form-group new-user-form'>
            <%= form_tag login_path, method: :post do %>
              <%= text_field_tag :email_address, nil, placeholder: "email address", class: "modal-form form-control" %><br>
              <%= password_field_tag :password, nil, placeholder: "password", class: "modal-form form-control" %><br>
              <%= submit_tag "Login", class: "btn btn-default" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/partials/_sign_up.html.erb
<a href="#" data-toggle="modal" data-target="#myModalLogIn">
  Sign-Up
</a>
<div class="modal fade" id="myModalLogIn" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel">Log into your account</h3>
      </div>
      <div class="modal-body">
        <div class="edit-form">
          <div class='form-group new-user-form'>
            <%= form_tag login_path, method: :post do %>
              <%= text_field_tag :email, nil, placeholder: "email address", class: "modal-form form-control" %><br>
              <%= password_field_tag :password, nil, placeholder: "password", class: "modal-form form-control" %><br>
              <%= submit_tag "Login", class: "btn btn-default" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/repos/_details.html.erb
<div class="repo-detail">
  <h1><%= @repo.owner %>'s <span class="light">project</span><br><%= @repo.name %></h1>
  <table data-sort-name="name" data-sort-order="desc" class="table table-hover table-condensed" id="detail-table">
    <tbody>
      <thead>
        <tr>
          <th data-field="message" data-align="center" data-sortable="true">Commit Message</th>
          <th data-field="sentiment" data-sortable="true">Sentiment</th>
        </tr>
      </thead>
    </tbody>
  </table>
    <% if !current_user %>
      <p>For fancy graphs and full analysis, sign up with github.</p>
      <a href="/auth/github"><i class="fa fa-github signup"></i></a>
    <% end %>
</div>

app/views/repos/create.js.erb
$(function() {
  $('div.row.mood-details').replaceWith('<%=j render 'repos/details' %>');
  $('#repoForm p').hide();
  d3.selectAll('svg').remove();
  moodRing();

  function moodRing() {
    analyze();

    function analyze() {
      var source = new EventSource('/commit_sentiments?id=<%= @repo.id %>');
      var start = 0,
          stop = 0.033,
          total = 0,
          commits = 0;

      source.onmessage = function (event){
        if (event.data === '"stream_end"') { 
          source.close(); 
          fullCircle(Math.round(total/commits)); 
          updateMood(total);
          $('#detail-table').bootstrapTable({
            search: false,
            columns: [{
              field: 'message',
              title: 'Commit Message',
              align: 'left',
              sortable: true
            }, {
              field: 'sentiment',
              title: 'Sentiment',
              align: 'right',
              sortable: true
            }]
          });
          $('.fixed-table-loading').hide();
          return 
        };

        var e = JSON.parse(event.data);
        score = +e["score"];
        total += score;
        circlePiece(start, stop, score);
        start += 0.033;
        stop += 0.033;
        commits += 1;
        $('#detail-table').find('tbody')
          .prepend($("<tr>")
              .append($("<td class='text-left'>")
                .text(e["msg"]))
              .append($("<td>")
                .text(score)));
      }
    }

    var width = 480,
        height = 250,
        twoPi = 2 * Math.PI,
        created = 0;

    var svg = d3.select("#circle").append("svg")
        .attr("width", width)
        .attr("height", height)
      .append("g")
        .attr("transform", "translate(" + width / 2 + "," + height / 2 + ")")

    var meter = svg.append("g")
        .attr("class", "progress-meter");


    var text = meter.append("text")
        .attr("text-anchor", "middle")
        .attr("dy", ".35em");

    var o = d3.scale.ordinal()
        .domain(d3.range(100))
        .range(["#e34a33", "#fdbb84", "#fee8c8", "#e5f5f9", "#99d8c9"]);

    function circlePiece(start, end, score) {
        var background = meter.append("path");
        var arc = d3.svg.arc()
          .startAngle(twoPi * start)
          .innerRadius(85)
          .outerRadius(95);

        svg.append("path").transition().duration(1000).tween("created", function() {
          var i = d3.interpolate(start,end);
          var c = d3.interpolateRgb('white', o(score));
              return function(t) {
                created = i(t);
                color = c(t);
                background.attr("d", arc.endAngle(twoPi * created))
                          .attr("fill", color);
                text.text(score.toString());
              };
        })
    }

    function fullCircle(total) {
        var background = meter.append("path");
        var arc = d3.svg.arc()
          .startAngle(0)
          .innerRadius(85)
          .outerRadius(95);

        svg.append("path").transition().duration(1000).tween("created", function() {
          var i = d3.interpolate(0,2);
          var c = d3.interpolateRgb('white', o(total));
              return function(t) {
                created = i(t);
                color = c(t);
                background.attr("d", arc.endAngle(twoPi * created))
                          .attr("fill", color);
                text.text(total.toString());
              };
        })
    }

    function updateMood(total) {
      $.ajax({
        type: "PATCH",
        url: "/repos/<%= @repo.id %>",
        data: { "mood": total }
      });
    }
  }
});

app/views/repos/failed.js.erb
$(function() {
  console.log("FAILED");
  d3.selectAll('svg').remove();
  $('#repoForm p').hide();
  $('div.row.mood-details').html("<p>The repo you entered was invalid. <a href='#' id='refresh'>Try again.</a></p>");
  $('#refresh').click(function() {
    location.reload();
  });
  failed();

  function failed() {
    var width = 480,
        height = 250,
        twoPi = 2 * Math.PI,
        created = 0;

    var arc = d3.svg.arc()
        .startAngle(0)
        .innerRadius(90)
        .outerRadius(95);

    var svg = d3.select("#circle").append("svg")
        .attr("width", width)
        .attr("height", height)
      .append("g")
        .attr("transform", "translate(" + width / 2 + "," + height / 2 + ")")

    var meter = svg.append("g")
        .attr("class", "progress-meter");

    var background = meter.append("path");

    var text = meter.append("text")
        .attr("text-anchor", "middle")
        .attr("dy", ".35em");

    svg.append("path").transition().duration(1000).tween("created", function() {
      var i = d3.interpolate(0,100);
      var c = d3.interpolateRgb('white', 'red');
          return function(t) {
            created = i(t);
            color = c(t);
            background.attr("d", arc.endAngle(twoPi * created))
                      .attr("fill", color);
            text.text("Failed");
          };
      })
  }

});

app/views/repos/show.html.erb
<div class="container">
  <div class="col-md-8 col-md-offset-2 text-center">
    <h1><%= @repo.name %></h1>
    <div id="show-circle"></div>
  </div>
  <div class="col-md-10 col-md-offset-1 text-center">
    <div id="show-graph"></div>
  </div>
</div>
<%= content_tag :div, class: "temp_information", data: {temp: @repo} do; end %>

app/views/users/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12 text-center">
      <h2>Sign Up</h2>
      <hr class="star-primary">
    </div>
  </div>
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2">
      <%= form_for @user, html: { id: "contactForm" } do |f| %>
        <div class="row-control-group">
          <div class="form-group col-xs-12 floating-label-form-group controls">
            <%= f.label :name %>
            <%= f.text_field :name, class: "form-control", placeholder: "Name" %>
          </div>
        </div>
        <div class="row-control-group">
          <div class="form-group col-xs-12 floating-label-form-group controls">
            <%= f.label :email %>
            <%= f.text_field :email, class: "form-control", placeholder: "Email Address" %>
          </div>
        </div>
        <div class="row-control-group">
          <div class="form-group col-xs-12 floating-label-form-group controls">
            <%= f.label :password %>
            <%= f.password_field :password, class: "form-control", placeholder: "Password" %>
          </div>
        </div>
        <div class="row-control-group">
          <div class="form-group col-xs-12 floating-label-form-group controls">
            <%= f.label :password_confirmation %>
            <%= f.password_field :password_confirmation, class: "form-control", placeholder: "Password Confirmation" %>
          </div>
        </div>
        <div class="form-group">
          <%= f.submit "Sign Up", class: "btn btn-default" %>
        </div>
      <% end %>
    </div>
  </div>

app/views/users/show.html.erb
<div class="col-md-6 col-md-offset-3">
  <h1 class="text-center"><%= @user.name %></h1>
  <h3 class="text-center">Public Repos</h3>
  <div class="list-group">
    <% @user.public_repos.each do |repo| %>
      <%= link_to "#{repo}", new_repo_path(repo: repo), class: "list-group-item" %>
    <% end %>
  </div>
  <% if @user.private_repos.any? %>
    <h3 class="text-center">Private Repos</h3>
    <div class="list-group">
      <% @user.private_repos.each do |repo| %>
        <a href="#" class="list-group-item"><%= repo %></a>
      <% end %>
    </div>
  <% end %>
</div>